#ifndef DEFAULT_MAVLINK_BRIDGE_APP_PLATFORM_CFG_H
#define DEFAULT_MAVLINK_BRIDGE_APP_PLATFORM_CFG_H

#define MAVLINK_BRIDGE_APP_PLATFORM_PIPE_DEPTH 32
#define MAVLINK_BRIDGE_APP_PLATFORM_PIPE_NAME  "MAVBRG_CMD"

#define MAVLINK_BRIDGE_APP_SERIAL_PATH         "/dev/serial0"
#define MAVLINK_BRIDGE_APP_SERIAL_BAUDRATE     230400
#define MAVLINK_BRIDGE_APP_SB_POLL_TIMEOUT_MS  200
#define MAVLINK_BRIDGE_APP_READ_CHUNK_SIZE     256

#endif
