#ifndef MAVLINK_BRIDGE_APP_VERSION_H
#define MAVLINK_BRIDGE_APP_VERSION_H

#define MAVLINK_BRIDGE_APP_BUILD_NUMBER    0
#define MAVLINK_BRIDGE_APP_BUILD_BASELINE  "v1.0.0"
#define MAVLINK_BRIDGE_APP_BUILD_DEV_CYCLE "v1.0.0"
#define MAVLINK_BRIDGE_APP_BUILD_CODENAME  "Draco"

#define MAVLINK_BRIDGE_APP_MAJOR_VERSION 1
#define MAVLINK_BRIDGE_APP_MINOR_VERSION 0
#define MAVLINK_BRIDGE_APP_REVISION      0

#define MAVLINK_BRIDGE_APP_LAST_OFFICIAL "v1.0.0"

/*
 * Mission revision is owned by mission configuration. Do not redefine it here.
 */

#define MAVLINK_BRIDGE_APP_STR_HELPER(x) #x
#define MAVLINK_BRIDGE_APP_STR(x) MAVLINK_BRIDGE_APP_STR_HELPER(x)

#define MAVLINK_BRIDGE_APP_VERSION \
    MAVLINK_BRIDGE_APP_BUILD_BASELINE "+dev" MAVLINK_BRIDGE_APP_STR(MAVLINK_BRIDGE_APP_BUILD_NUMBER)

#define MAVLINK_BRIDGE_APP_CFG_MAX_VERSION_STR_LEN 256

#endif
