#ifndef LORA_FC_DOWNLINK_APP_VERSION_H
#define LORA_FC_DOWNLINK_APP_VERSION_H

#define LORA_FC_DOWNLINK_APP_MAJOR_VERSION 1
#define LORA_FC_DOWNLINK_APP_MINOR_VERSION 0
#define LORA_FC_DOWNLINK_APP_REVISION      0
#define LORA_FC_DOWNLINK_APP_MISSION_REV   0

#define LORA_FC_DOWNLINK_APP_VERSION " 1.0.0.0"
#define LORA_FC_DOWNLINK_APP_BUILD_CODENAME "dev"
#define LORA_FC_DOWNLINK_APP_LAST_OFFICIAL "v1.0.0"
#define LORA_FC_DOWNLINK_APP_CFG_MAX_VERSION_STR_LEN 256

#endif
