#ifndef DEFAULT_LORA_FC_DOWNLINK_APP_FCNCODE_VALUES_H
#define DEFAULT_LORA_FC_DOWNLINK_APP_FCNCODE_VALUES_H

#define LORA_FC_DOWNLINK_APP_NOOP_CC            0
#define LORA_FC_DOWNLINK_APP_RESET_COUNTERS_CC  1

#endif
