#ifndef DEFAULT_LORA_FC_DOWNLINK_APP_MSGIDS_H
#define DEFAULT_LORA_FC_DOWNLINK_APP_MSGIDS_H

#include "lora_fc_downlink_app_msgid_values.h"

#define LORA_FC_DOWNLINK_APP_CMD_MID      LORA_FC_DOWNLINK_APP_CMD_PLATFORM_MIDVAL(CMD)
#define LORA_FC_DOWNLINK_APP_SEND_HK_MID  LORA_FC_DOWNLINK_APP_CMD_PLATFORM_MIDVAL(SEND_HK)
#define LORA_FC_DOWNLINK_APP_HK_TLM_MID   LORA_FC_DOWNLINK_APP_TLM_PLATFORM_MIDVAL(HK_TLM)

#endif
