#ifndef LORA_FC_DOWNLINK_APP_EVENTS_H
#define LORA_FC_DOWNLINK_APP_EVENTS_H

#define LORA_FC_DOWNLINK_APP_RESERVED_EID     0
#define LORA_FC_DOWNLINK_APP_INIT_INF_EID     1
#define LORA_FC_DOWNLINK_APP_CC_ERR_EID       2
#define LORA_FC_DOWNLINK_APP_NOOP_INF_EID     3
#define LORA_FC_DOWNLINK_APP_RESET_INF_EID    4
#define LORA_FC_DOWNLINK_APP_MID_ERR_EID      5
#define LORA_FC_DOWNLINK_APP_CMD_LEN_ERR_EID  6
#define LORA_FC_DOWNLINK_APP_PIPE_ERR_EID     7
#define LORA_FC_DOWNLINK_APP_CR_PIPE_ERR_EID  8
#define LORA_FC_DOWNLINK_APP_SUB_HK_ERR_EID   9
#define LORA_FC_DOWNLINK_APP_SUB_CMD_ERR_EID  10

#endif
