#ifndef LORA_FC_DOWNLINK_APP_INTERNAL_CFG_H
#define LORA_FC_DOWNLINK_APP_INTERNAL_CFG_H

#include "lora_fc_downlink_app_internal_cfg_values.h"

#define LORA_FC_DOWNLINK_APP_PLATFORM_PIPE_DEPTH         LORA_FC_DOWNLINK_APP_PLATFORM_CFGVAL(PIPE_DEPTH)
#define DEFAULT_LORA_FC_DOWNLINK_APP_PLATFORM_PIPE_DEPTH 10

#define LORA_FC_DOWNLINK_APP_PLATFORM_PIPE_NAME         LORA_FC_DOWNLINK_APP_PLATFORM_CFGVAL(PIPE_NAME)
#define DEFAULT_LORA_FC_DOWNLINK_APP_PLATFORM_PIPE_NAME "LORA_FC_DN_CMD_PIPE"

#endif
