#ifndef MAVLINK_BRIDGE_APP_EVENTIDS_H
#define MAVLINK_BRIDGE_APP_EVENTIDS_H

#define MAVLINK_BRIDGE_APP_STARTUP_EID     1
#define MAVLINK_BRIDGE_APP_COMMAND_ERR_EID 2
#define MAVLINK_BRIDGE_APP_NOOP_EID        3
#define MAVLINK_BRIDGE_APP_RESET_EID       4
#define MAVLINK_BRIDGE_APP_LINK_EID        5
#define MAVLINK_BRIDGE_APP_PARSE_EID       6

#endif
