#ifndef DEFAULT_MAVLINK_BRIDGE_APP_INTERFACE_CFG_VALUES_H
#define DEFAULT_MAVLINK_BRIDGE_APP_INTERFACE_CFG_VALUES_H

#define MAVLINK_BRIDGE_APP_CMD_MID_VALUE     0x18A0
#define MAVLINK_BRIDGE_APP_SEND_HK_MID_VALUE 0x18A1

#define FC_EKF_LOCAL_STATE_MID_VALUE         0x1905
#define FC_ATTITUDE_STATE_MID_VALUE          0x1906
#define FC_GPS_RAW_STATE_MID_VALUE           0x1907
#define FC_EKF_STATUS_MID_VALUE              0x1908

#endif
