#ifndef DEFAULT_IMG_APP_INTERNAL_CFG_VALUES_H
#define DEFAULT_IMG_APP_INTERNAL_CFG_VALUES_H

#define IMG_APP_PLATFORM_PIPE_DEPTH  16
#define IMG_APP_PLATFORM_PIPE_NAME   "IMG_CMD"
#define IMG_APP_SB_POLL_TIMEOUT_MS   200
#define IMG_APP_PROTOTYPE_PERIOD_MS  1000

#endif
