#ifndef DEFAULT_IMG_APP_MSGDEFS_H
#define DEFAULT_IMG_APP_MSGDEFS_H

typedef enum
{
    IMG_APP_TIMESTAMP_QUALITY_AUTHORITATIVE_CAPTURE = 0,
    IMG_APP_TIMESTAMP_QUALITY_CFS_SNAPSHOT_ESTIMATE = 1,
    IMG_APP_TIMESTAMP_QUALITY_RX_ONLY_ESTIMATE      = 2
} IMG_APP_TimestampQuality_t;

typedef enum
{
    IMG_APP_TRANSFER_PENDING   = 0,
    IMG_APP_TRANSFER_AVAILABLE = 1,
    IMG_APP_TRANSFER_FAILED    = 2
} IMG_APP_TransferStatus_t;

typedef enum
{
    IMG_APP_CORRELATION_UNSET       = 0,
    IMG_APP_CORRELATION_ESTIMATED   = 1,
    IMG_APP_CORRELATION_CORRELATED  = 2,
    IMG_APP_CORRELATION_UNCERTAIN   = 3
} IMG_APP_CorrelationStatus_t;

#endif
