#ifndef DEFAULT_IMG_APP_INTERFACE_CFG_VALUES_H
#define DEFAULT_IMG_APP_INTERFACE_CFG_VALUES_H

#define IMG_APP_CMD_MID_VALUE      0x18B0
#define IMG_APP_SEND_HK_MID_VALUE  0x18B1
#define IMAGE_META_MID_VALUE       0x1904

#endif
