#ifndef DEFAULT_MAVLINK_BRIDGE_APP_MSGDEFS_H
#define DEFAULT_MAVLINK_BRIDGE_APP_MSGDEFS_H

typedef enum
{
    MAVLINK_BRIDGE_LINK_DISCONNECTED = 0,
    MAVLINK_BRIDGE_LINK_DEGRADED     = 1,
    MAVLINK_BRIDGE_LINK_CONNECTED    = 2
} MAVLINK_BRIDGE_APP_LinkState_t;

typedef enum
{
    MAVLINK_BRIDGE_ERROR_NONE = 0,
    MAVLINK_BRIDGE_ERROR_LINK_DOWN,
    MAVLINK_BRIDGE_ERROR_READ_TIMEOUT,
    MAVLINK_BRIDGE_ERROR_SERIAL_OPEN_FAIL,
    MAVLINK_BRIDGE_ERROR_PARSE_FAIL,
    MAVLINK_BRIDGE_ERROR_UNSUPPORTED_MSG,
    MAVLINK_BRIDGE_ERROR_STALE_DATA,
    MAVLINK_BRIDGE_ERROR_EKF_UNHEALTHY,
    MAVLINK_BRIDGE_ERROR_GPS_NO_FIX,
    MAVLINK_BRIDGE_ERROR_INVALID_VALUE,
    MAVLINK_BRIDGE_ERROR_TIMESTAMP_INVALID
} MAVLINK_BRIDGE_APP_ErrorCode_t;

#endif
