#ifndef DEFAULT_MAVLINK_BRIDGE_APP_FCNCODE_VALUES_H
#define DEFAULT_MAVLINK_BRIDGE_APP_FCNCODE_VALUES_H

#define MAVLINK_BRIDGE_APP_NOOP_CC           0
#define MAVLINK_BRIDGE_APP_RESET_COUNTERS_CC 1

#endif
